//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class adk_GRADES_APOUSIES_OUTPUT
    {
        public long ROW_ID { get; set; }
        public Nullable<int> ΜΑΘΗΤΗΣ_ΚΩΔ { get; set; }
        public Nullable<int> ΚΩΔ_ΤΜΗΜΑ { get; set; }
        public string ΜΑΘΗΜΑ { get; set; }
        public Nullable<double> ΜΟΒΠ { get; set; }
        public Nullable<double> ΜΟΤΕ { get; set; }
        public Nullable<double> ΜΟΕΠ { get; set; }
        public Nullable<double> ΜΟ { get; set; }
        public Nullable<int> ΣΥΝΟΛΟ_ΩΡΕΣ { get; set; }
        public Nullable<decimal> ΟΡΙΟ { get; set; }
        public Nullable<int> ΑΠΟΥΣΙΕΣ { get; set; }
        public string ΑΠΟΤΕΛΕΣΜΑ { get; set; }
        public decimal ΒΕ { get; set; }
    }
}
