//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class adk_STUDENT_PRAKTIKI
    {
        public int ΕΡΓ_ΠΡΑΚΤΙΚΗ_ΚΩΔ { get; set; }
        public Nullable<int> STUDENT_ID { get; set; }
        public Nullable<int> ΙΕΚ { get; set; }
        public string ΕΡΓΟΔΟΤΗΣ_ΕΠΩΝΥΜΙΑ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΑΠΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΕΩΣ { get; set; }
        public Nullable<int> ΩΡΕΣ { get; set; }
        public string ΠΕΡΙΟΔΟΣ { get; set; }
    }
}
