//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class adk_ΤΜΗΜΑ_ΠΕΡΙΟΔΟΣ
    {
        public int ΤΜΗΜΑ_ΚΩΔ { get; set; }
        public int TERM_ID { get; set; }
        public string TERM_TEXT { get; set; }
        public string ΠΕΡΙΟΔΟΣ { get; set; }
        public int PERIOD_ID { get; set; }
        public Nullable<int> ΧΕ_ΚΩΔ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public string SY_TEXT { get; set; }
    }
}
