//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class adk_GRADES_GMO_OUTPUT
    {
        public long ROW_ID { get; set; }
        public int STUDENT_ID { get; set; }
        public Nullable<int> ΚΩΔ_ΤΜΗΜΑ { get; set; }
        public Nullable<int> LESSON_TERM { get; set; }
        public Nullable<int> LESSON_COUNT { get; set; }
        public Nullable<double> GRADES_SUM { get; set; }
        public Nullable<double> ΓΜΟ { get; set; }
    }
}
