//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bek_STUDENTS_TABLE
    {
        public int STUDENT_ID { get; set; }
        public int ΑΜΚ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public Nullable<int> ΕΙΔΙΚΟΤΗΤΑ { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public string TERM { get; set; }
        public string ΠΕΡΙΟΔΟΣ { get; set; }
        public int ΙΕΚ { get; set; }
    }
}
