//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sqlΜΑΘΗΜΑ_ΠΑΡΑΚΟΛΟΥΘΗΣΗ
    {
        public string ΠΕΡΙΟΔΟΣ { get; set; }
        public int ΙΕΚ { get; set; }
        public int EIDIKOTITA_ID { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public int ΚΩΔ_ΤΜΗΜΑ { get; set; }
        public string ΤΜΗΜΑ_ΟΝΟΜΑ { get; set; }
        public int LESSON_ID { get; set; }
        public string LESSON_TEXT { get; set; }
        public Nullable<int> ΚΩΔ_ΕΡΓΑΣΙΑ { get; set; }
        public string ΕΡΓΑΣΙΑ { get; set; }
        public int TERM_ID { get; set; }
        public string TERM_TEXT { get; set; }
        public Nullable<int> ΩΡΕΣ_ΜΑΘΗΜΑ { get; set; }
        public Nullable<int> ΩΡΕΣ_ΟΡΙΟ { get; set; }
        public Nullable<int> ΥΠΟΛΟΙΠΟ { get; set; }
    }
}
