//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOITISI_DELTIA
    {
        public int ROW_ID { get; set; }
        public Nullable<int> ΣΧΟΛΕΙΟ { get; set; }
        public Nullable<int> ΜΑΘΗΤΗΣ_ΚΩΔ { get; set; }
        public Nullable<int> ΚΩΔ_ΤΜΗΜΑ { get; set; }
        public string ΜΑΘΗΜΑ { get; set; }
        public Nullable<int> ΜΟΒΠ { get; set; }
        public Nullable<int> ΜΟΤΕ { get; set; }
        public Nullable<int> ΜΟΕΠ { get; set; }
        public Nullable<int> ΜΟ { get; set; }
        public Nullable<int> ΣΥΝΟΛΟ_ΩΡΕΣ { get; set; }
        public Nullable<int> ΟΡΙΟ { get; set; }
        public Nullable<int> ΑΠΟΥΣΙΕΣ { get; set; }
        public string ΑΠΟΤΕΛΕΣΜΑ { get; set; }
        public Nullable<int> LESSON_COUNT { get; set; }
        public Nullable<int> GRADES_SUM { get; set; }
        public Nullable<decimal> ΓΜΟ { get; set; }
        public Nullable<int> TERM_ID { get; set; }
        public string TERM_TEXT { get; set; }
        public string ΠΕΡΙΟΔΟΣ { get; set; }
        public Nullable<int> PERIOD_ID { get; set; }
        public Nullable<int> ΧΕ_ΚΩΔ { get; set; }
        public string SY_TEXT { get; set; }
        public Nullable<int> ΕΓΓΡΑΦΗ_ΕΙΔΟΣ { get; set; }
        public Nullable<int> ΦΟΙΤΗΣΗ { get; set; }
        public Nullable<decimal> ΒΕ { get; set; }
    }
}
