//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LESSON_TYPES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LESSON_TYPES()
        {
            this.LESSONS_IEK = new HashSet<LESSONS_IEK>();
        }
    
        public int LESSON_TYPE_ID { get; set; }
        public string LESSON_TYPE_TEXT { get; set; }
        public string LESSON_TYPE_TAG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LESSONS_IEK> LESSONS_IEK { get; set; }
    }
}
