//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LESSONS_IEK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LESSONS_IEK()
        {
            this.ΜΑΘΗΤΕΣ_ΒΑΘΜΟΙ = new HashSet<ΜΑΘΗΤΕΣ_ΒΑΘΜΟΙ>();
        }
    
        public int LESSON_ID { get; set; }
        public string LESSON_TEXT { get; set; }
        public Nullable<int> LESSON_TERM { get; set; }
        public Nullable<int> LESSON_TYPE { get; set; }
        public Nullable<int> LESSON_HOURS_WEEK { get; set; }
        public Nullable<int> LESSON_HOURS { get; set; }
        public Nullable<int> LESSON_EIDIKOTITA { get; set; }
    
        public virtual LESSON_TYPES LESSON_TYPES { get; set; }
        public virtual SYS_TERM SYS_TERM { get; set; }
        public virtual SYS_EIDIKOTITES_IEK SYS_EIDIKOTITES_IEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΜΑΘΗΤΕΣ_ΒΑΘΜΟΙ> ΜΑΘΗΤΕΣ_ΒΑΘΜΟΙ { get; set; }
    }
}
