//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProteusDBEntities : DbContext
    {
        public ProteusDBEntities()
            : base("name=ProteusDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IEK_EIDIKOTITES> IEK_EIDIKOTITES { get; set; }
        public virtual DbSet<LESSON_TYPES> LESSON_TYPES { get; set; }
        public virtual DbSet<LESSONS_IEK> LESSONS_IEK { get; set; }
        public virtual DbSet<SYS_DIMOS> SYS_DIMOS { get; set; }
        public virtual DbSet<SYS_EIDIKOTITES_GROUPS> SYS_EIDIKOTITES_GROUPS { get; set; }
        public virtual DbSet<SYS_GENDERS> SYS_GENDERS { get; set; }
        public virtual DbSet<SYS_KLADOS> SYS_KLADOS { get; set; }
        public virtual DbSet<SYS_PERIFERIAKES> SYS_PERIFERIAKES { get; set; }
        public virtual DbSet<SYS_PERIFERIES> SYS_PERIFERIES { get; set; }
        public virtual DbSet<SYS_SCHOOLS> SYS_SCHOOLS { get; set; }
        public virtual DbSet<SYS_SCHOOLYEARS> SYS_SCHOOLYEARS { get; set; }
        public virtual DbSet<SYS_TERM> SYS_TERM { get; set; }
        public virtual DbSet<USER_ADMINS> USER_ADMINS { get; set; }
        public virtual DbSet<USER_SCHOOLS> USER_SCHOOLS { get; set; }
        public virtual DbSet<ΑΠΟΛΥΤΗΡΙΑ> ΑΠΟΛΥΤΗΡΙΑ { get; set; }
        public virtual DbSet<ΕΓΓΡΑΦΗ_ΕΙΔΗ> ΕΓΓΡΑΦΗ_ΕΙΔΗ { get; set; }
        public virtual DbSet<ΕΡΓΑΣΙΕΣ> ΕΡΓΑΣΙΕΣ { get; set; }
        public virtual DbSet<ΕΤΗ> ΕΤΗ { get; set; }
        public virtual DbSet<ΜΑΘΗΜΑ_ΧΑΡΑΚΤΗΡΙΣΜΟΣ> ΜΑΘΗΜΑ_ΧΑΡΑΚΤΗΡΙΣΜΟΣ { get; set; }
        public virtual DbSet<ΠΑ> ΠΑ { get; set; }
        public virtual DbSet<ΠΡΑΞΕΙΣ_ΕΙΣΟΔΟΥ> ΠΡΑΞΕΙΣ_ΕΙΣΟΔΟΥ { get; set; }
        public virtual DbSet<ΠΡΑΞΕΙΣ_ΕΞΟΔΟΥ> ΠΡΑΞΕΙΣ_ΕΞΟΔΟΥ { get; set; }
        public virtual DbSet<ΣΠΟΥΔΕΣ> ΣΠΟΥΔΕΣ { get; set; }
        public virtual DbSet<ΥΠΑΛΛΗΛΟΣ> ΥΠΑΛΛΗΛΟΣ { get; set; }
        public virtual DbSet<ΥΠΗΚΟΟΤΗΤΑ> ΥΠΗΚΟΟΤΗΤΑ { get; set; }
        public virtual DbSet<ΦΟΙΤΗΣΗ> ΦΟΙΤΗΣΗ { get; set; }
        public virtual DbSet<ΧΕ> ΧΕ { get; set; }
        public virtual DbSet<sqlUSER_SCHOOL> sqlUSER_SCHOOL { get; set; }
        public virtual DbSet<VS_DIMOS_PERIFERIA> VS_DIMOS_PERIFERIA { get; set; }
        public virtual DbSet<VS_EIDIKOTITES_DataView> VS_EIDIKOTITES_DataView { get; set; }
        public virtual DbSet<VS_EIDIKOTITES_MasterView> VS_EIDIKOTITES_MasterView { get; set; }
        public virtual DbSet<PROGRAMMA_BUFFER> PROGRAMMA_BUFFER { get; set; }
        public virtual DbSet<ΕΚΠΑΙΔΕΥΤΕΣ_ΑΝΑΘΕΣΕΙΣ> ΕΚΠΑΙΔΕΥΤΕΣ_ΑΝΑΘΕΣΕΙΣ { get; set; }
        public virtual DbSet<ΕΚΠΑΙΔΕΥΤΕΣ_ΠΕΡΙΟΔΟΙ> ΕΚΠΑΙΔΕΥΤΕΣ_ΠΕΡΙΟΔΟΙ { get; set; }
        public virtual DbSet<ΠΕΡΙΟΔΟΙ> ΠΕΡΙΟΔΟΙ { get; set; }
        public virtual DbSet<ΜΑΘΗΤΕΣ_ΒΑΘΜΟΙ> ΜΑΘΗΤΕΣ_ΒΑΘΜΟΙ { get; set; }
        public virtual DbSet<ΜΑΘΗΤΕΣ_ΕΓΓΡΑΦΕΣ> ΜΑΘΗΤΕΣ_ΕΓΓΡΑΦΕΣ { get; set; }
        public virtual DbSet<viewIEK_EIDIKOTITES> viewIEK_EIDIKOTITES { get; set; }
        public virtual DbSet<ΜΑΘΗΤΕΣ> ΜΑΘΗΤΕΣ { get; set; }
        public virtual DbSet<sqlEGRAFES_INFO> sqlEGRAFES_INFO { get; set; }
        public virtual DbSet<qryIEK_EIDIKOTITES> qryIEK_EIDIKOTITES { get; set; }
        public virtual DbSet<qrySTUDENT_SELECTOR> qrySTUDENT_SELECTOR { get; set; }
        public virtual DbSet<ΕΡΓΟΔΟΤΕΣ> ΕΡΓΟΔΟΤΕΣ { get; set; }
        public virtual DbSet<ΕΡΓΟΔΟΤΕΣ_ΠΡΑΚΤΙΚΗ> ΕΡΓΟΔΟΤΕΣ_ΠΡΑΚΤΙΚΗ { get; set; }
        public virtual DbSet<qryEIDIKOTITES_SELECTOR> qryEIDIKOTITES_SELECTOR { get; set; }
        public virtual DbSet<qryTEACHER_SELECTOR> qryTEACHER_SELECTOR { get; set; }
        public virtual DbSet<sqlTEACHER_INFO> sqlTEACHER_INFO { get; set; }
        public virtual DbSet<sqlTEACHER_PERIODS_INFO> sqlTEACHER_PERIODS_INFO { get; set; }
        public virtual DbSet<qryLESSON_SELECTOR> qryLESSON_SELECTOR { get; set; }
        public virtual DbSet<qryIEK_EIDIKOTITES_LESSONS> qryIEK_EIDIKOTITES_LESSONS { get; set; }
        public virtual DbSet<qrySTUDENT_PRAKTIKI_SELECTOR> qrySTUDENT_PRAKTIKI_SELECTOR { get; set; }
        public virtual DbSet<sqlTEACHER_ANATHESEIS_INFO> sqlTEACHER_ANATHESEIS_INFO { get; set; }
        public virtual DbSet<qryTMIMA_PRAKTIKI_SELECTOR> qryTMIMA_PRAKTIKI_SELECTOR { get; set; }
        public virtual DbSet<sqlPRAKTIKI_INFO> sqlPRAKTIKI_INFO { get; set; }
        public virtual DbSet<qrySTUDENT_GLOBAL_SELECTOR> qrySTUDENT_GLOBAL_SELECTOR { get; set; }
        public virtual DbSet<ΕΚΠΑΙΔΕΥΤΕΣ_ΑΙΤΗΣΕΙΣ> ΕΚΠΑΙΔΕΥΤΕΣ_ΑΙΤΗΣΕΙΣ { get; set; }
        public virtual DbSet<sqlANATHESEIS_VIEW> sqlANATHESEIS_VIEW { get; set; }
        public virtual DbSet<ΠΡΑΚΤΙΚΗ_ΑΙΤΗΣΗ> ΠΡΑΚΤΙΚΗ_ΑΙΤΗΣΗ { get; set; }
        public virtual DbSet<ΠΡΑΚΤΙΚΗ_ΑΠΟΦΑΣΗ> ΠΡΑΚΤΙΚΗ_ΑΠΟΦΑΣΗ { get; set; }
        public virtual DbSet<ΠΡΑΚΤΙΚΗ_ΕΛΕΓΧΟΣ> ΠΡΑΚΤΙΚΗ_ΕΛΕΓΧΟΣ { get; set; }
        public virtual DbSet<ΠΡΑΚΤΙΚΗ_ΠΑΡΟΥΣΙΑ> ΠΡΑΚΤΙΚΗ_ΠΑΡΟΥΣΙΑ { get; set; }
        public virtual DbSet<ΠΡΑΚΤΙΚΗ_ΠΕΡΑΤΩΣΗ> ΠΡΑΚΤΙΚΗ_ΠΕΡΑΤΩΣΗ { get; set; }
        public virtual DbSet<sqlAITISEIS_PRAKTIKIS_VIEW> sqlAITISEIS_PRAKTIKIS_VIEW { get; set; }
        public virtual DbSet<regΜΑΘΗΤΕΣ_ΒΕΒΑΙΩΣΕΙΣ> regΜΑΘΗΤΕΣ_ΒΕΒΑΙΩΣΕΙΣ { get; set; }
        public virtual DbSet<regΠΡΑΚΤΙΚΗ_ΑΙΤΗΣΕΙΣ> regΠΡΑΚΤΙΚΗ_ΑΙΤΗΣΕΙΣ { get; set; }
        public virtual DbSet<regΠΡΑΚΤΙΚΗ_ΑΠΟΦΑΣΕΙΣ> regΠΡΑΚΤΙΚΗ_ΑΠΟΦΑΣΕΙΣ { get; set; }
        public virtual DbSet<regΠΡΑΚΤΙΚΗ_ΠΑΡΟΥΣΙΕΣ> regΠΡΑΚΤΙΚΗ_ΠΑΡΟΥΣΙΕΣ { get; set; }
        public virtual DbSet<regΠΡΑΚΤΙΚΗ_ΠΕΡΑΤΩΣΗ> regΠΡΑΚΤΙΚΗ_ΠΕΡΑΤΩΣΗ { get; set; }
        public virtual DbSet<regΠΡΑΚΤΙΚΗ_ΕΛΕΓΧΟΙ> regΠΡΑΚΤΙΚΗ_ΕΛΕΓΧΟΙ { get; set; }
        public virtual DbSet<qrySTUDENT_TMIMA_SELECTOR> qrySTUDENT_TMIMA_SELECTOR { get; set; }
        public virtual DbSet<NUMBERS> NUMBERS { get; set; }
        public virtual DbSet<ΤΜΗΜΑ> ΤΜΗΜΑ { get; set; }
        public virtual DbSet<sqlΤΜΗΜΑΤΑ> sqlΤΜΗΜΑΤΑ { get; set; }
        public virtual DbSet<ΜΑΘΗΤΕΣ_ΑΠΟΥΣΙΕΣ> ΜΑΘΗΤΕΣ_ΑΠΟΥΣΙΕΣ { get; set; }
        public virtual DbSet<ΜΑΘΗΤΕΣ_ΑΠΟΥΣΙΕΣ2> ΜΑΘΗΤΕΣ_ΑΠΟΥΣΙΕΣ2 { get; set; }
        public virtual DbSet<ΠΡΟΓΡΑΜΜΑ_ΗΜΕΡΑ> ΠΡΟΓΡΑΜΜΑ_ΗΜΕΡΑ { get; set; }
        public virtual DbSet<qrySTUDENT_BEK_SELECTOR> qrySTUDENT_BEK_SELECTOR { get; set; }
        public virtual DbSet<sqlSTUDENTS_BEK_APOUSIES> sqlSTUDENTS_BEK_APOUSIES { get; set; }
        public virtual DbSet<sqlΕΙΔΙΚΟΤΗΤΕΣ_ΙΕΚ_ΩΡΕΣ> sqlΕΙΔΙΚΟΤΗΤΕΣ_ΙΕΚ_ΩΡΕΣ { get; set; }
        public virtual DbSet<sqlΕΙΔΙΚΟΤΗΤΕΣ_ΙΕΚ_ΩΡΕΣ_ΓΔ> sqlΕΙΔΙΚΟΤΗΤΕΣ_ΙΕΚ_ΩΡΕΣ_ΓΔ { get; set; }
        public virtual DbSet<sqlΠΡΑΚΤΙΚΗ_ΜΑΘΗΤΗΣ_ΩΡΕΣ> sqlΠΡΑΚΤΙΚΗ_ΜΑΘΗΤΗΣ_ΩΡΕΣ { get; set; }
        public virtual DbSet<ΜΑΘΗΤΕΣ_ΒΕΚ> ΜΑΘΗΤΕΣ_ΒΕΚ { get; set; }
        public virtual DbSet<sqlΤΜΗΜΑΤΑ_ΒΕΚ> sqlΤΜΗΜΑΤΑ_ΒΕΚ { get; set; }
        public virtual DbSet<ΕΚΠΑΙΔΕΥΤΕΣ_ΒΕΒΑΙΩΣΕΙΣ> ΕΚΠΑΙΔΕΥΤΕΣ_ΒΕΒΑΙΩΣΕΙΣ { get; set; }
        public virtual DbSet<sqlΜΑΘΗΤΕΣ_ΤΜΗΜΑ_ΕΝΕΡΓΟΙ> sqlΜΑΘΗΤΕΣ_ΤΜΗΜΑ_ΕΝΕΡΓΟΙ { get; set; }
        public virtual DbSet<sqlΜΑΘΗΤΕΣ_ΑΠΟΥΣΙΕΣ_ΑΝΑΛΥΤΙΚΟ> sqlΜΑΘΗΤΕΣ_ΑΠΟΥΣΙΕΣ_ΑΝΑΛΥΤΙΚΟ { get; set; }
        public virtual DbSet<sqlΜΑΘΗΤΕΣ_ΒΑΘΜΟΙ_ΜΙΚΤΑ> sqlΜΑΘΗΤΕΣ_ΒΑΘΜΟΙ_ΜΙΚΤΑ { get; set; }
        public virtual DbSet<sqlΜΑΘΗΜΑ_ΠΑΡΑΚΟΛΟΥΘΗΣΗ> sqlΜΑΘΗΜΑ_ΠΑΡΑΚΟΛΟΥΘΗΣΗ { get; set; }
        public virtual DbSet<qryIEK_LESSONS_IN_PROGRAMMADAY> qryIEK_LESSONS_IN_PROGRAMMADAY { get; set; }
        public virtual DbSet<ΑΠΟΧΩΡΗΣΗ_ΑΙΤΙΕΣ> ΑΠΟΧΩΡΗΣΗ_ΑΙΤΙΕΣ { get; set; }
        public virtual DbSet<ΕΚΠΑΙΔΕΥΤΕΣ_ΑΠΟΧΩΡΗΣΕΙΣ> ΕΚΠΑΙΔΕΥΤΕΣ_ΑΠΟΧΩΡΗΣΕΙΣ { get; set; }
        public virtual DbSet<sqlTEACHERS_IN_PERIODS> sqlTEACHERS_IN_PERIODS { get; set; }
        public virtual DbSet<ΕΚΠΑΙΔΕΥΤΕΣ_ΑΝΑΛΗΨΕΙΣ> ΕΚΠΑΙΔΕΥΤΕΣ_ΑΝΑΛΗΨΕΙΣ { get; set; }
        public virtual DbSet<sqlTEACHERS_WITH_PERIODS> sqlTEACHERS_WITH_PERIODS { get; set; }
        public virtual DbSet<ΑΠΑΣΧΟΛΗΣΗ> ΑΠΑΣΧΟΛΗΣΗ { get; set; }
        public virtual DbSet<sqlSTUDENTS_PRAKTIKI_REGISTRY> sqlSTUDENTS_PRAKTIKI_REGISTRY { get; set; }
        public virtual DbSet<sqlΜΑΘΗΤΕΣ_ΒΑΘΜΟΙ_ΘΕ> sqlΜΑΘΗΤΕΣ_ΒΑΘΜΟΙ_ΘΕ { get; set; }
        public virtual DbSet<sqlΤΜΗΜΑΤΑ_ΧΕ> sqlΤΜΗΜΑΤΑ_ΧΕ { get; set; }
        public virtual DbSet<ΜΑΘΗΤΕΣ_ΑΠΑΛΛΑΓΕΣ> ΜΑΘΗΤΕΣ_ΑΠΑΛΛΑΓΕΣ { get; set; }
        public virtual DbSet<adk_LESSON_NAMES> adk_LESSON_NAMES { get; set; }
        public virtual DbSet<adk_STUDENT_INFO> adk_STUDENT_INFO { get; set; }
        public virtual DbSet<ΣΥΣ_ΕΝΤΥΠΑ> ΣΥΣ_ΕΝΤΥΠΑ { get; set; }
        public virtual DbSet<sqlSTUDENTS_TMIMA_ACTIVE> sqlSTUDENTS_TMIMA_ACTIVE { get; set; }
        public virtual DbSet<ΣΥΣ_ΕΝΤΥΠΑ_ΙΕΚ> ΣΥΣ_ΕΝΤΥΠΑ_ΙΕΚ { get; set; }
        public virtual DbSet<sqlSTUDENTS_PRAKTIKI_APALLAGI> sqlSTUDENTS_PRAKTIKI_APALLAGI { get; set; }
        public virtual DbSet<sqlSTUDENTS_PRAKTIKI_DIAKOPI> sqlSTUDENTS_PRAKTIKI_DIAKOPI { get; set; }
        public virtual DbSet<sqlSTUDENTS_PRAKTIKI_EXPLORE> sqlSTUDENTS_PRAKTIKI_EXPLORE { get; set; }
        public virtual DbSet<sqlSTUDENTS_IN_PRAKTIKI> sqlSTUDENTS_IN_PRAKTIKI { get; set; }
        public virtual DbSet<SYS_REGIONS> SYS_REGIONS { get; set; }
        public virtual DbSet<SYS_KLADOS_ENIAIOS> SYS_KLADOS_ENIAIOS { get; set; }
        public virtual DbSet<SYS_EIDIKOTITES_IEK> SYS_EIDIKOTITES_IEK { get; set; }
        public virtual DbSet<SYS_EIDIKOTITES> SYS_EIDIKOTITES { get; set; }
        public virtual DbSet<SYS_EIDIKOTITES_OLD> SYS_EIDIKOTITES_OLD { get; set; }
        public virtual DbSet<sqlEIDIKOTITES> sqlEIDIKOTITES { get; set; }
        public virtual DbSet<VD_EIDIKOTITES> VD_EIDIKOTITES { get; set; }
        public virtual DbSet<SYS_LOGINS> SYS_LOGINS { get; set; }
        public virtual DbSet<sqlSCHOOL_LOGINS> sqlSCHOOL_LOGINS { get; set; }
        public virtual DbSet<APP_STATUS> APP_STATUS { get; set; }
        public virtual DbSet<ΧΜ_ΑΠΟΤΕΛΕΣΜΑ> ΧΜ_ΑΠΟΤΕΛΕΣΜΑ { get; set; }
        public virtual DbSet<ΧΜ_sqlΕΠΙΛΑΧΟΝΤΕΣ> ΧΜ_sqlΕΠΙΛΑΧΟΝΤΕΣ { get; set; }
        public virtual DbSet<ΧΜ_sqlΕΠΙΤΥΧΟΝΤΕΣ> ΧΜ_sqlΕΠΙΤΥΧΟΝΤΕΣ { get; set; }
        public virtual DbSet<ΧΜ_sqlΕΜΠΕΙΡΙΑ_ΜΗΝΕΣ> ΧΜ_sqlΕΜΠΕΙΡΙΑ_ΜΗΝΕΣ { get; set; }
        public virtual DbSet<asrc_ΜΑΘΗΤΕΣ_ΒΑΘΜΟΙ_ΘΕ> asrc_ΜΑΘΗΤΕΣ_ΒΑΘΜΟΙ_ΘΕ { get; set; }
        public virtual DbSet<ΕΚΠΑΙΔΕΥΤΕΣ> ΕΚΠΑΙΔΕΥΤΕΣ { get; set; }
        public virtual DbSet<ΜΑΘΗΤΕΣ_ΑΙΤΗΣΕΙΣ> ΜΑΘΗΤΕΣ_ΑΙΤΗΣΕΙΣ { get; set; }
        public virtual DbSet<ΜΑΘΗΤΕΣ_ΑΤΟΜΙΚΑΔΕΛΤΙΑ> ΜΑΘΗΤΕΣ_ΑΤΟΜΙΚΑΔΕΛΤΙΑ { get; set; }
        public virtual DbSet<ΜΑΘΗΤΕΣ_ΒΕΒΑΙΩΣΕΙΣ> ΜΑΘΗΤΕΣ_ΒΕΒΑΙΩΣΕΙΣ { get; set; }
        public virtual DbSet<bek_STUDENTS_TABLE> bek_STUDENTS_TABLE { get; set; }
        public virtual DbSet<sqlSTUDENTS_APOUSIES_LESSON> sqlSTUDENTS_APOUSIES_LESSON { get; set; }
        public virtual DbSet<sqlEIDIKOTITES_KU> sqlEIDIKOTITES_KU { get; set; }
        public virtual DbSet<adk_ΤΜΗΜΑ_ΠΕΡΙΟΔΟΣ> adk_ΤΜΗΜΑ_ΠΕΡΙΟΔΟΣ { get; set; }
        public virtual DbSet<ATOMIKA_DELTIA> ATOMIKA_DELTIA { get; set; }
        public virtual DbSet<adk_GRADES_APOUSIES_OUTPUT> adk_GRADES_APOUSIES_OUTPUT { get; set; }
        public virtual DbSet<adk_STUDENT_DATA> adk_STUDENT_DATA { get; set; }
        public virtual DbSet<adk_STUDENT_PRAKTIKI> adk_STUDENT_PRAKTIKI { get; set; }
        public virtual DbSet<adk_GRADES_GMO_OUTPUT> adk_GRADES_GMO_OUTPUT { get; set; }
        public virtual DbSet<ΠΡΟΓΡΑΜΜΑ_ΑΡΧΕΙΟ> ΠΡΟΓΡΑΜΜΑ_ΑΡΧΕΙΟ { get; set; }
        public virtual DbSet<C_sqlΜΑΘΗΜΑ_ΠΑΡΑΚΟΛΟΥΘΗΣΗ> C_sqlΜΑΘΗΜΑ_ΠΑΡΑΚΟΛΟΥΘΗΣΗ { get; set; }
        public virtual DbSet<sqlIEK_LESSONS> sqlIEK_LESSONS { get; set; }
        public virtual DbSet<FOITISI_DELTIA> FOITISI_DELTIA { get; set; }
        public virtual DbSet<ΜΑΘΗΤΕΣ_ΦΟΙΤΗΣΗΔΕΛΤΙΑ> ΜΑΘΗΤΕΣ_ΦΟΙΤΗΣΗΔΕΛΤΙΑ { get; set; }
        public virtual DbSet<ΧΜ_ΕΓΚΥΚΛΙΟΣ> ΧΜ_ΕΓΚΥΚΛΙΟΣ { get; set; }
        public virtual DbSet<ΧΜ_ΕΓΚΥΚΛΙΟΣ_ΚΑΘΕΣΤΩΣ> ΧΜ_ΕΓΚΥΚΛΙΟΣ_ΚΑΘΕΣΤΩΣ { get; set; }
        public virtual DbSet<USER_STUDENTS> USER_STUDENTS { get; set; }
        public virtual DbSet<TAXISNET> TAXISNET { get; set; }
        public virtual DbSet<ΧΜ_ΥΠΟΨΗΦΙΟΣ_ΕΜΠΕΙΡΙΑ> ΧΜ_ΥΠΟΨΗΦΙΟΣ_ΕΜΠΕΙΡΙΑ { get; set; }
        public virtual DbSet<ΧΜ_sqlAITISEIS_HEADERS> ΧΜ_sqlAITISEIS_HEADERS { get; set; }
        public virtual DbSet<ΧΜ_ΕΙΔΙΚΟΤΗΤΕΣ> ΧΜ_ΕΙΔΙΚΟΤΗΤΕΣ { get; set; }
        public virtual DbSet<ΧΜ_ΕΓΚΥΚΛΙΟΣ_ΕΙΔΙΚΟΤΗΤΕΣ> ΧΜ_ΕΓΚΥΚΛΙΟΣ_ΕΙΔΙΚΟΤΗΤΕΣ { get; set; }
        public virtual DbSet<ΧΜ_sqlEIDIKOTITA_SELECTOR> ΧΜ_sqlEIDIKOTITA_SELECTOR { get; set; }
        public virtual DbSet<ΧΜ_UPLOADS> ΧΜ_UPLOADS { get; set; }
        public virtual DbSet<ΧΜ_UPLOADS_FILES> ΧΜ_UPLOADS_FILES { get; set; }
        public virtual DbSet<ΧΜ_ΥΠΟΨΗΦΙΟΣ> ΧΜ_ΥΠΟΨΗΦΙΟΣ { get; set; }
        public virtual DbSet<xmUSER_STUDENT_SELECT> xmUSER_STUDENT_SELECT { get; set; }
        public virtual DbSet<ΧΜ_ΕΘΝΙΚΟΤΗΤΑ> ΧΜ_ΕΘΝΙΚΟΤΗΤΑ { get; set; }
        public virtual DbSet<ΧΜ_sqlUPLOADED_FILES> ΧΜ_sqlUPLOADED_FILES { get; set; }
        public virtual DbSet<ΕΞΕΤΑΣΗ_ΚΑΤΗΓΟΡΙΕΣ> ΕΞΕΤΑΣΗ_ΚΑΤΗΓΟΡΙΕΣ { get; set; }
        public virtual DbSet<ΑΠΟΛΥΤΗΡΙΑ_ΚΛΑΣΕΙΣ> ΑΠΟΛΥΤΗΡΙΑ_ΚΛΑΣΕΙΣ { get; set; }
        public virtual DbSet<qryIEK_EIDIKOTITA_LESSON_TEXT> qryIEK_EIDIKOTITA_LESSON_TEXT { get; set; }
        public virtual DbSet<STUDENT_GRADES> STUDENT_GRADES { get; set; }
        public virtual DbSet<sqlSTUDENT_INFO> sqlSTUDENT_INFO { get; set; }
        public virtual DbSet<ΘΕΜΑΤΙΚΕΣ_ΕΙΔΗ> ΘΕΜΑΤΙΚΕΣ_ΕΙΔΗ { get; set; }
        public virtual DbSet<STUDENT_ERGASIES> STUDENT_ERGASIES { get; set; }
    }
}
