//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryIEK_EIDIKOTITA_LESSON_TEXT
    {
        public long ROW_ID { get; set; }
        public int IEK_ID { get; set; }
        public Nullable<int> LESSON_EIDIKOTITA { get; set; }
        public Nullable<int> LESSON_TERM { get; set; }
        public string LESSON_TEXT { get; set; }
    }
}
