//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryLESSON_SELECTOR
    {
        public int LESSON_ID { get; set; }
        public string LESSON_DESC { get; set; }
        public Nullable<int> LESSON_EIDIKOTITA { get; set; }
        public Nullable<int> LESSON_TERM { get; set; }
    }
}
