//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class qrySTUDENT_BEK_SELECTOR
    {
        public int STUDENT_ID { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public int ΑΜΚ { get; set; }
        public int ΙΕΚ { get; set; }
        public Nullable<int> ΚΩΔ_ΤΜΗΜΑ { get; set; }
        public string ΤΜΗΜΑ_ΟΝΟΜΑ { get; set; }
        public Nullable<int> ΕΙΔΙΚΟΤΗΤΑ_ΚΩΔ { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public int ΣΠΟΥΔΕΣ_ΔΙΑΡΚΕΙΑ { get; set; }
        public string ΠΑΤΡΩΝΥΜΟ { get; set; }
        public string ΜΗΤΡΩΝΥΜΟ { get; set; }
        public Nullable<int> ΦΥΛΟ { get; set; }
        public Nullable<bool> ΠΡΑΚΤΙΚΗ_ΑΠΑΛΛΑΓΗ { get; set; }
        public Nullable<bool> ΑΠΟ_ΚΑΤΑΤΑΞΗ { get; set; }
        public Nullable<bool> ΜΕ_ΕΠΑΡΚΕΙΑ_ΩΡΕΣ { get; set; }
    }
}
