//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class regΠΡΑΚΤΙΚΗ_ΑΙΤΗΣΕΙΣ
    {
        public int STUDENT_ID { get; set; }
        public int ΑΜΚ { get; set; }
        public int ΙΕΚ { get; set; }
        public string SCHOOL_NAME { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public string GENDER { get; set; }
        public string ΕΡΓΟΔΟΤΗΣ_ΕΠΩΝΥΜΙΑ { get; set; }
        public string ΥΠΕΥΘΥΝΟΣ { get; set; }
        public Nullable<int> ΠΡΩΤΟΚΟΛΛΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΕΡΟΜΗΝΙΑ { get; set; }
        public Nullable<System.DateTime> ΠΡΑΚΤΙΚΗ_ΑΠΟ { get; set; }
        public Nullable<System.DateTime> ΠΡΑΚΤΙΚΗ_ΕΩΣ { get; set; }
        public Nullable<int> ΠΡΑΚΤΙΚΗ_ΩΡΕΣ { get; set; }
        public int ΑΙΤΗΣΗ_ΚΩΔ { get; set; }
        public string ΕΡΓΟΔΟΤΗΣ_ΑΦΜ { get; set; }
        public string ΤΗΛΕΦΩΝΑ { get; set; }
        public string ΔΙΕΥΘΥΝΣΗ { get; set; }
        public string ΠΕΡΙΓΡΑΦΗ { get; set; }
    }
}
