//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlEIDIKOTITES_KU
    {
        public int EIDIKOTITA_ID { get; set; }
        public string EIDIKOTITA_PTYXIO { get; set; }
        public Nullable<int> KLADOS_UNIFIED { get; set; }
        public Nullable<int> EIDIKOTITA_KLADOS_ID { get; set; }
    }
}
