//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlEGRAFES_INFO
    {
        public string ΤΜΗΜΑ_ΟΝΟΜΑ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΕΓΓΡΑΦΗ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΠΕΡΑΣ { get; set; }
        public string ΕΓΓΡΑΦΗ_ΕΙΔΟΣ_ΛΕΚΤΙΚΟ { get; set; }
        public string ΦΟΙΤΗΣΗ_ΛΕΚΤΙΚΟ { get; set; }
        public Nullable<int> ΑΜΚ { get; set; }
        public Nullable<int> ΙΕΚ { get; set; }
        public int ΜΕ_ΚΩΔ { get; set; }
        public Nullable<int> ΜΑΘΗΤΗΣ_ΚΩΔ { get; set; }
    }
}
