//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlPRAKTIKI_INFO
    {
        public int ΕΡΓ_ΠΡΑΚΤΙΚΗ_ΚΩΔ { get; set; }
        public Nullable<int> ΙΕΚ { get; set; }
        public string ΤΜΗΜΑ_ΟΝΟΜΑ { get; set; }
        public Nullable<int> ΜΑΘΗΤΗΣ_ΑΜΚ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string ΕΡΓΟΔΟΤΗΣ_ΕΠΩΝΥΜΙΑ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΑΠΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΕΩΣ { get; set; }
        public Nullable<int> ΩΡΕΣ { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public Nullable<int> ΜΑΘΗΤΗΣ_ΚΩΔ { get; set; }
        public Nullable<int> ΕΡΓΟΔΟΤΗΣ_ΚΩΔΙΚΟΣ { get; set; }
    }
}
