//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlSTUDENT_INFO
    {
        public int STUDENT_ID { get; set; }
        public int ΑΜΚ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public string ΑΦΜ { get; set; }
        public string ΑΜΚΑ { get; set; }
        public string ΠΑΤΡΩΝΥΜΟ { get; set; }
        public string ΜΗΤΡΩΝΥΜΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΓΕΝΝΗΣΗ { get; set; }
        public string ΔΙΕΥΘΥΝΣΗ { get; set; }
        public string ΤΗΛΕΦΩΝΑ { get; set; }
        public string ΑΠΟΛΥΤΗΡΙΟ_ΛΕΚΤΙΚΟ { get; set; }
        public Nullable<System.DateTime> ΠΡΑΞΗ_ΕΙΣΟΔΟΥ_ΗΜΝΙΑ { get; set; }
        public string ΠΡΑΞΗ_ΕΙΣΟΔΟΥ { get; set; }
        public Nullable<int> ΣΠΟΥΔΕΣ_ΔΙΑΡΚΕΙΑ { get; set; }
        public Nullable<short> ΗΛΙΚΙΑ { get; set; }
        public string ΥΠΗΚΟΟΤΗΤΑ_ΛΕΚΤΙΚΟ { get; set; }
        public int ΙΕΚ { get; set; }
        public string GENDER { get; set; }
        public string ΠΡΑΞΗ_ΕΞΟΔΟΥ { get; set; }
    }
}
