//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlSTUDENTS_PRAKTIKI_REGISTRY
    {
        public string SY_TEXT { get; set; }
        public string ΠΕΡΙΟΔΟΣ { get; set; }
        public int ΑΜΚ { get; set; }
        public int ΙΕΚ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string SCHOOL_NAME { get; set; }
        public string ΤΜΗΜΑ_ΟΝΟΜΑ { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public string ΕΡΓΟΔΟΤΗΣ_ΕΠΩΝΥΜΙΑ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΑΠΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΕΩΣ { get; set; }
        public Nullable<int> ΩΡΕΣ { get; set; }
        public string ΠΕΡΙΓΡΑΦΗ { get; set; }
        public string ΕΡΓΟΔΟΤΗΣ_ΑΦΜ { get; set; }
        public string ΥΠΕΥΘΥΝΟΣ { get; set; }
        public string ΤΗΛΕΦΩΝΑ { get; set; }
        public string ΔΙΕΥΘΥΝΣΗ { get; set; }
        public int STUDENT_ID { get; set; }
        public int SY_ID { get; set; }
        public int PERIOD_ID { get; set; }
        public int SCHOOL_ID { get; set; }
        public int ΤΜΗΜΑ_ΚΩΔ { get; set; }
        public int ΕΡΓ_ΠΡΑΚΤΙΚΗ_ΚΩΔ { get; set; }
        public int ΕΡΓΟΔΟΤΗΣ_ΚΩΔ { get; set; }
    }
}
