//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlSTUDENTS_TMIMA_ACTIVE
    {
        public int ΙΕΚ { get; set; }
        public int STUDENT_ID { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public Nullable<int> ΚΩΔ_ΤΜΗΜΑ { get; set; }
        public Nullable<int> ΠΡΑΞΗ_ΕΞΟΔΟΥ_ΕΙΔΟΣ { get; set; }
    }
}
