//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlTEACHER_INFO
    {
        public int TEACHER_ID { get; set; }
        public string ΑΦΜ { get; set; }
        public int ΙΕΚ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string GENDER { get; set; }
        public string ΑΜΚΑ { get; set; }
        public string ΑΜΑ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΓΕΝΝΗΣΗ { get; set; }
        public string ΔΙΕΥΘΥΝΣΗ { get; set; }
        public string ΤΗΛΕΦΩΝΑ { get; set; }
        public string EMAIL { get; set; }
        public string KLADOS_NAME { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΠΡΟΣΛΗΨΗ { get; set; }
        public Nullable<int> ΗΛΙΚΙΑ { get; set; }
        public string ΥΠΑΛΛΗΛΟΣ_ΛΕΚΤΙΚΟ { get; set; }
        public string ΠΑΤΡΩΝΥΜΟ { get; set; }
        public string ΜΗΤΡΩΝΥΜΟ { get; set; }
    }
}
