//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlTEACHERS_IN_PERIODS
    {
        public int TEACHER_ID { get; set; }
        public string ΑΦΜ { get; set; }
        public int ΙΕΚ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string KLADOS_NAME { get; set; }
        public string EIDIKOTITA_DESC { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΠΡΟΣΛΗΨΗΣ { get; set; }
        public int PERIOD_ID { get; set; }
        public string ΠΕΡΙΟΔΟΣ { get; set; }
        public int SY_ID { get; set; }
        public string SY_TEXT { get; set; }
        public string ΠΑΤΡΩΝΥΜΟ { get; set; }
        public Nullable<int> ΦΥΛΟ { get; set; }
        public string ΠΑΤΡΩΝΥΜΟ_ΓΕΝΙΚΗ { get; set; }
    }
}
