//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlTEACHER_ANATHESEIS_INFO
    {
        public int TEACHER_ID { get; set; }
        public string ΑΦΜ { get; set; }
        public int ΙΕΚ { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public string LESSON_DESC { get; set; }
        public Nullable<short> ΩΡΕΣ_ΘΕΩΡΙΑ { get; set; }
        public Nullable<short> ΩΡΕΣ_ΕΡΓΑΣΤΗΡΙΟ { get; set; }
        public Nullable<short> ΣΥΝΟΛΟ { get; set; }
        public int ΕΑ_ΚΩΔ { get; set; }
    }
}
