//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlTEACHER_PERIODS_INFO
    {
        public int ΕΠ_ΚΩΔ { get; set; }
        public string ΑΦΜ { get; set; }
        public Nullable<int> ΙΕΚ { get; set; }
        public string ΠΕΡΙΟΔΟΣ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΠΡΟΣΛΗΨΗΣ { get; set; }
        public string ΑΠΟΦΑΣΗ { get; set; }
        public string ΑΔΑ { get; set; }
        public Nullable<int> TEACHER_ID { get; set; }
    }
}
