//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlΜΑΘΗΤΕΣ_ΒΑΘΜΟΙ_ΜΙΚΤΑ
    {
        public int ΙΕΚ { get; set; }
        public int STUDENT_ID { get; set; }
        public int ΑΜΚ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string ΠΕΡΙΟΔΟΣ { get; set; }
        public int TERM_ID { get; set; }
        public string TERM_TEXT { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public Nullable<int> ΚΩΔ_ΤΜΗΜΑ { get; set; }
        public string ΤΜΗΜΑ_ΟΝΟΜΑ { get; set; }
        public string ΜΑΘΗΜΑ { get; set; }
        public Nullable<double> ΜΟΒΠ { get; set; }
        public Nullable<double> ΜΟΤΕ { get; set; }
        public Nullable<double> ΜΟΕΠ { get; set; }
        public Nullable<double> ΓΜΟ { get; set; }
        public int EIDIKOTITA_ID { get; set; }
        public decimal ΒΕ { get; set; }
        public string ΠΑΤΡΩΝΥΜΟ_ΓΕΝΙΚΗ { get; set; }
        public string ΜΗΤΡΩΝΥΜΟ_ΓΕΝΙΚΗ { get; set; }
        public Nullable<int> ΑΠΟΛΥΤΗΡΙΟ_ΚΩΔ { get; set; }
        public Nullable<int> ΦΥΛΟ { get; set; }
    }
}
