//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlΜΑΘΗΤΕΣ_ΒΑΘΜΟΙ_ΘΕ
    {
        public int ΜΒ_ΚΩΔ { get; set; }
        public int ΙΕΚ { get; set; }
        public int STUDENT_ID { get; set; }
        public int ΑΜΚ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string ΠΕΡΙΟΔΟΣ { get; set; }
        public int TERM_ID { get; set; }
        public string TERM_TEXT { get; set; }
        public int EIDIKOTITA_ID { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public Nullable<int> ΚΩΔ_ΤΜΗΜΑ { get; set; }
        public string ΤΜΗΜΑ_ΟΝΟΜΑ { get; set; }
        public string ΜΑΘΗΜΑ { get; set; }
        public Nullable<float> ΒΑΘΜΟΣ_ΠΡΟΟΔΟΥ { get; set; }
        public Nullable<float> ΒΑΘΜΟΣ_ΤΕ { get; set; }
        public Nullable<float> ΒΑΘΜΟΣ_ΕΠ { get; set; }
        public Nullable<float> ΒΑΘΜΟΣ_ΜΟ { get; set; }
    }
}
