//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlΤΜΗΜΑΤΑ_ΧΕ
    {
        public int ΤΜΗΜΑ_ΚΩΔ { get; set; }
        public string ΠΕΡΙΟΔΟΣ { get; set; }
        public Nullable<int> ΧΕ_ΚΩΔ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΛΗΞΗΣ { get; set; }
    }
}
