//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlΠΡΑΚΤΙΚΗ_ΜΑΘΗΤΗΣ_ΩΡΕΣ
    {
        public int STUDENT_ID { get; set; }
        public int ΑΜΚ { get; set; }
        public int ΙΕΚ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public Nullable<System.DateTime> ΑΡΧΙΚΗ { get; set; }
        public Nullable<System.DateTime> ΤΕΛΙΚΗ { get; set; }
        public Nullable<int> ΣΥΝΟΛΟ_ΩΡΕΣ { get; set; }
    }
}
