//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlΤΜΗΜΑΤΑ_ΒΕΚ
    {
        public int ΤΜΗΜΑ_ΚΩΔ { get; set; }
        public Nullable<int> ΙΕΚ { get; set; }
        public string ΤΜΗΜΑ_ΟΝΟΜΑ { get; set; }
        public int EIDIKOTITA_ID { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public string TERM { get; set; }
        public int TERM_ID { get; set; }
        public string ΠΕΡΙΟΔΟΣ { get; set; }
    }
}
