//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_GRADES
    {
        public int GRADES_ID { get; set; }
        public Nullable<int> IEK { get; set; }
        public string PERIOD_TEXT { get; set; }
        public Nullable<int> STUDENT_ID { get; set; }
        public Nullable<int> AMK { get; set; }
        public string FULLNAME { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public string TERM_TEXT { get; set; }
        public string LESSON_TEXT { get; set; }
        public Nullable<int> TMIMA_ID { get; set; }
        public Nullable<int> EIDIKOTITA_ID { get; set; }
        public Nullable<int> TERM_ID { get; set; }
        public Nullable<decimal> ΠΡΘ { get; set; }
        public Nullable<decimal> ΠΡΕ { get; set; }
        public Nullable<decimal> ΤΕΘ { get; set; }
        public Nullable<decimal> ΤΕΕ { get; set; }
        public Nullable<decimal> ΕΠ { get; set; }
        public Nullable<decimal> ΠΡΟΟΔΟΣ { get; set; }
        public Nullable<decimal> ΕΡΓΑΣΙΑ { get; set; }
        public Nullable<decimal> ΕΞΕΤΑΣΗ { get; set; }
        public Nullable<decimal> ΤΕΛΙΚΟΣ { get; set; }
    }
}
