//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_SCHOOLS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_SCHOOLS()
        {
            this.ΕΡΓΟΔΟΤΕΣ = new HashSet<ΕΡΓΟΔΟΤΕΣ>();
            this.ΤΜΗΜΑ = new HashSet<ΤΜΗΜΑ>();
            this.ΕΚΠΑΙΔΕΥΤΕΣ = new HashSet<ΕΚΠΑΙΔΕΥΤΕΣ>();
        }
    
        public int SCHOOL_ID { get; set; }
        public string SCHOOL_NAME { get; set; }
        public Nullable<int> SCHOOL_PERIFERIA_ID { get; set; }
        public Nullable<int> SCHOOL_DIMOS { get; set; }
        public Nullable<int> SCHOOL_PERIFERIAKI_ID { get; set; }
        public string SCHOOL_ADDRESS { get; set; }
        public string SCHOOL_TK_CITY { get; set; }
        public string SCHOOL_EMAIL { get; set; }
        public string SCHOOL_PHONE { get; set; }
        public string SCHOOL_FAX { get; set; }
        public string SCHOOL_DIRECTOR { get; set; }
        public string SCHOOL_DEPUTY { get; set; }
        public string SCHOOL_INFO { get; set; }
        public Nullable<int> DIRECTOR_GENDER { get; set; }
        public Nullable<int> DEPUTY_GENDER { get; set; }
        public Nullable<int> SCHOOL_REGION_ID { get; set; }
    
        public virtual SYS_PERIFERIAKES SYS_PERIFERIAKES { get; set; }
        public virtual SYS_PERIFERIES SYS_PERIFERIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΕΡΓΟΔΟΤΕΣ> ΕΡΓΟΔΟΤΕΣ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΤΜΗΜΑ> ΤΜΗΜΑ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΕΚΠΑΙΔΕΥΤΕΣ> ΕΚΠΑΙΔΕΥΤΕΣ { get; set; }
    }
}
