//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_EIDIKOTITES
    {
        public int EIDIKOTITA_ID { get; set; }
        public string EIDIKOTITA_CODE { get; set; }
        public string EIDIKOTITA_UNIFIED { get; set; }
        public string EIDIKOTITA_NAME { get; set; }
        public Nullable<int> KLADOS_UNIFIED { get; set; }
        public Nullable<int> EIDIKOTITA_KLADOS_ID { get; set; }
    
        public virtual SYS_KLADOS_ENIAIOS SYS_KLADOS_ENIAIOS { get; set; }
        public virtual SYS_KLADOS SYS_KLADOS { get; set; }
    }
}
