//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_KLADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_KLADOS()
        {
            this.SYS_EIDIKOTITES = new HashSet<SYS_EIDIKOTITES>();
        }
    
        public int KLADOS_ID { get; set; }
        public string KLADOS_NAME { get; set; }
        public string KLADOS_CATEGORY { get; set; }
        public Nullable<int> KLADOS_HOURS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_EIDIKOTITES> SYS_EIDIKOTITES { get; set; }
    }
}
