//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAXISNET
    {
        public int TAXISNET_ID { get; set; }
        public Nullable<int> RANDOM_NUMBER { get; set; }
        public string TAXISNET_AFM { get; set; }
    }
}
