//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VS_EIDIKOTITES_MasterView
    {
        public string EIDIKOTITA_CODE { get; set; }
        public string EIDIKOTITA_NAME { get; set; }
        public string KLADOS_NAME { get; set; }
        public int KLADOS_ID { get; set; }
    }
}
