//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΑΠΟΛΥΤΗΡΙΑ
    {
        public int ΑΠΟΛΥΤΗΡΙΟ_ΚΩΔΙΚΟΣ { get; set; }
        public string ΑΠΟΛΥΤΗΡΙΟ_ΛΕΚΤΙΚΟ { get; set; }
        public Nullable<int> ΑΠΟΛΥΤΗΡΙΟ_ΚΛΑΣΗ { get; set; }
    }
}
