//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΑΠΑΣΧΟΛΗΣΗ
    {
        public int ΑΠΑΣΧΟΛΗΣΗ_ΚΩΔ { get; set; }
        public string ΑΠΑΣΧΟΛΗΣΗ_ΛΕΚΤΙΚΟ { get; set; }
    }
}
