//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΑΠΟΧΩΡΗΣΗ_ΑΙΤΙΕΣ
    {
        public int ΑΠΟΧΩΡΗΣΗ_ΚΩΔΙΚΟΣ { get; set; }
        public string ΑΠΟΧΩΡΗΣΗ_ΑΙΤΙΑ { get; set; }
    }
}
