//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΕΚΠΑΙΔΕΥΤΕΣ_ΑΝΑΘΕΣΕΙΣ
    {
        public int ΕΑ_ΚΩΔ { get; set; }
        public string ΑΦΜ { get; set; }
        public Nullable<int> ΙΕΚ { get; set; }
        public Nullable<int> ΕΙΔΙΚΟΤΗΤΑ { get; set; }
        public Nullable<int> ΠΕΡΙΟΔΟΣ_ΚΩΔ { get; set; }
        public Nullable<int> ΜΑΘΗΜΑ_ΚΩΔ { get; set; }
        public Nullable<int> ΕΞΑΜΗΝΟ { get; set; }
        public Nullable<short> ΩΡΕΣ_ΘΕΩΡΙΑ { get; set; }
        public Nullable<short> ΩΡΕΣ_ΕΡΓΑΣΤΗΡΙΟ { get; set; }
        public Nullable<short> ΣΥΝΟΛΟ { get; set; }
        public Nullable<int> TEACHER_ID { get; set; }
    
        public virtual ΕΚΠΑΙΔΕΥΤΕΣ ΕΚΠΑΙΔΕΥΤΕΣ { get; set; }
    }
}
