//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΕΚΠΑΙΔΕΥΤΕΣ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ΕΚΠΑΙΔΕΥΤΕΣ()
        {
            this.ΕΚΠΑΙΔΕΥΤΕΣ_ΑΙΤΗΣΕΙΣ = new HashSet<ΕΚΠΑΙΔΕΥΤΕΣ_ΑΙΤΗΣΕΙΣ>();
            this.ΕΚΠΑΙΔΕΥΤΕΣ_ΑΝΑΘΕΣΕΙΣ = new HashSet<ΕΚΠΑΙΔΕΥΤΕΣ_ΑΝΑΘΕΣΕΙΣ>();
            this.ΕΚΠΑΙΔΕΥΤΕΣ_ΒΕΒΑΙΩΣΕΙΣ = new HashSet<ΕΚΠΑΙΔΕΥΤΕΣ_ΒΕΒΑΙΩΣΕΙΣ>();
            this.ΕΚΠΑΙΔΕΥΤΕΣ_ΠΕΡΙΟΔΟΙ = new HashSet<ΕΚΠΑΙΔΕΥΤΕΣ_ΠΕΡΙΟΔΟΙ>();
        }
    
        public int TEACHER_ID { get; set; }
        public string ΑΦΜ { get; set; }
        public int ΙΕΚ { get; set; }
        public string ΕΠΩΝΥΜΟ { get; set; }
        public string ΟΝΟΜΑ { get; set; }
        public string ΠΑΤΡΩΝΥΜΟ { get; set; }
        public string ΜΗΤΡΩΝΥΜΟ { get; set; }
        public string ΠΑΤΡΩΝΥΜΟ_ΓΕΝΙΚΗ { get; set; }
        public string ΜΗΤΡΩΝΥΜΟ_ΓΕΝΙΚΗ { get; set; }
        public Nullable<int> ΦΥΛΟ { get; set; }
        public string ΔΟΥ { get; set; }
        public string ΑΜΚΑ { get; set; }
        public string ΑΜΑ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΓΕΝΝΗΣΗ { get; set; }
        public string ΔΙΕΥΘΥΝΣΗ { get; set; }
        public string ΤΗΛΕΦΩΝΑ { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> ΚΛΑΔΟΣ { get; set; }
        public Nullable<int> ΕΙΔΙΚΟΤΗΤΑ { get; set; }
        public string ΕΙΔΙΚΟΤΗΤΑ_ΚΩΔΙΚΟΣ { get; set; }
        public Nullable<int> ΠΤΥΧΙΟ { get; set; }
        public Nullable<bool> MASTER { get; set; }
        public Nullable<bool> ΔΙΔΑΚΤΟΡΙΚΟ { get; set; }
        public Nullable<bool> ΠΑΙΔΑΓΩΓΙΚΟ { get; set; }
        public Nullable<int> ΥΠΑΛΛΗΛΟΣ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΠΡΟΣΛΗΨΗ { get; set; }
        public Nullable<int> ΗΛΙΚΙΑ { get; set; }
        public string ΠΑΡΑΤΗΡΗΣΕΙΣ { get; set; }
        public string ΑΔΤ { get; set; }
        public Nullable<int> ΤΕΚΝΑ { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_ACCOUNT { get; set; }
        public string BANK_IBAN { get; set; }
        public string ΜΙΣΘΟΔΟΣΙΑ_ΚΩΔ { get; set; }
    
        public virtual SYS_SCHOOLS SYS_SCHOOLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΕΚΠΑΙΔΕΥΤΕΣ_ΑΙΤΗΣΕΙΣ> ΕΚΠΑΙΔΕΥΤΕΣ_ΑΙΤΗΣΕΙΣ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΕΚΠΑΙΔΕΥΤΕΣ_ΑΝΑΘΕΣΕΙΣ> ΕΚΠΑΙΔΕΥΤΕΣ_ΑΝΑΘΕΣΕΙΣ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΕΚΠΑΙΔΕΥΤΕΣ_ΒΕΒΑΙΩΣΕΙΣ> ΕΚΠΑΙΔΕΥΤΕΣ_ΒΕΒΑΙΩΣΕΙΣ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΕΚΠΑΙΔΕΥΤΕΣ_ΠΕΡΙΟΔΟΙ> ΕΚΠΑΙΔΕΥΤΕΣ_ΠΕΡΙΟΔΟΙ { get; set; }
    }
}
