//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΕΚΠΑΙΔΕΥΤΕΣ_ΒΕΒΑΙΩΣΕΙΣ
    {
        public int ΒΕΒΑΙΩΣΗ_ΚΩΔ { get; set; }
        public Nullable<int> TEACHER_ID { get; set; }
        public string ΑΦΜ { get; set; }
        public Nullable<int> ΙΕΚ { get; set; }
        public Nullable<int> ΠΡΩΤΟΚΟΛΛΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΕΡΟΜΗΝΙΑ { get; set; }
        public string ΓΙΑ_ΧΡΗΣΗ { get; set; }
        public Nullable<bool> ΠΑΡΑΔΟΔΗΚΕ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
    
        public virtual ΕΚΠΑΙΔΕΥΤΕΣ ΕΚΠΑΙΔΕΥΤΕΣ { get; set; }
    }
}
