//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΕΡΓΟΔΟΤΕΣ_ΠΡΑΚΤΙΚΗ
    {
        public int ΕΡΓ_ΠΡΑΚΤΙΚΗ_ΚΩΔ { get; set; }
        public Nullable<int> ΕΡΓΟΔΟΤΗΣ_ΚΩΔΙΚΟΣ { get; set; }
        public Nullable<int> ΙΕΚ { get; set; }
        public Nullable<int> ΤΜΗΜΑ_ΚΩΔ { get; set; }
        public Nullable<int> ΜΑΘΗΤΗΣ_ΑΜΚ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΑΠΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΕΩΣ { get; set; }
        public Nullable<int> ΩΡΕΣ { get; set; }
        public string ΑΝΤΙΚΕΙΜΕΝΟ { get; set; }
        public string ΠΕΡΙΓΡΑΦΗ { get; set; }
        public Nullable<System.DateTime> ΒΕΒΑΙΩΣΗ_ΗΜΝΙΑ { get; set; }
        public Nullable<int> ΜΑΘΗΤΗΣ_ΚΩΔ { get; set; }
    
        public virtual ΕΡΓΟΔΟΤΕΣ ΕΡΓΟΔΟΤΕΣ { get; set; }
    }
}
