//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΜΑΘΗΤΕΣ_ΑΠΟΥΣΙΕΣ
    {
        public int ΜΑ_ΚΩΔ { get; set; }
        public Nullable<int> ΑΜΚ { get; set; }
        public Nullable<int> ΙΕΚ { get; set; }
        public Nullable<System.DateTime> ΗΜΕΡΟΜΗΝΙΑ { get; set; }
        public Nullable<int> ΚΩΔ_ΜΑΘΗΜΑ { get; set; }
        public Nullable<int> ΚΩΔ_ΤΜΗΜΑ { get; set; }
        public Nullable<int> ΩΡΕΣ_ΑΠΟΥΣΙΑ { get; set; }
        public Nullable<int> ΜΑΘΗΤΗΣ_ΚΩΔ { get; set; }
    
        public virtual ΜΑΘΗΤΕΣ ΜΑΘΗΤΕΣ { get; set; }
    }
}
