//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΜΑΘΗΤΕΣ_ΒΕΚ
    {
        public int ΜΑΘΗΤΗΣ_ΒΕΚ_ΚΩΔ { get; set; }
        public Nullable<int> ΑΜΚ { get; set; }
        public Nullable<int> ΙΕΚ { get; set; }
        public Nullable<int> ΚΩΔ_ΤΜΗΜΑ { get; set; }
        public string ΑΡ_ΒΙΒΛΙΟΥ_ΒΕΚ { get; set; }
        public string ΕΠΩΝΥΜΟ_ΟΝΟΜΑ { get; set; }
        public string ΠΑΤΡΩΝΥΜΟ { get; set; }
        public string ΜΗΤΡΩΝΥΜΟ { get; set; }
        public Nullable<int> ΕΙΔΙΚΟΤΗΤΑ { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public Nullable<bool> ΑΠΑΛΛΑΓΗ_ΠΡΑΚΤΙΚΗΣ { get; set; }
        public Nullable<bool> ΑΠΟ_ΚΑΤΑΤΑΞΗ { get; set; }
        public Nullable<bool> ΜΕ_ΕΠΑΡΚΕΙΑ_ΩΡΕΣ { get; set; }
        public Nullable<int> ΕΞΑΜΗΝΑ { get; set; }
        public Nullable<int> ΔΙΑΡΚΕΙΑ_ΣΥΝΟΛΙΚΗ { get; set; }
        public Nullable<int> ΔΙΑΡΚΕΙΑ_ΘΕΩΡΙΑ { get; set; }
        public Nullable<int> ΔΙΑΡΚΕΙΑ_ΠΡΑΚΤΙΚΗ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΕΚΔΟΣΗΣ_ΒΕΚ { get; set; }
        public Nullable<bool> ΕΚΔΟΣΗ { get; set; }
        public Nullable<int> ΜΑΘΗΤΗΣ_ΚΩΔ { get; set; }
    
        public virtual ΜΑΘΗΤΕΣ ΜΑΘΗΤΕΣ { get; set; }
    }
}
