//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΜΑΘΗΤΕΣ_ΦΟΙΤΗΣΗΔΕΛΤΙΑ
    {
        public int ΑΔΚ_ΚΩΔ { get; set; }
        public Nullable<int> ΜΑΘΗΤΗΣ_ΚΩΔ { get; set; }
        public Nullable<int> ΙΕΚ { get; set; }
        public Nullable<int> ΠΡΩΤΟΚΟΛΛΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΕΡΟΜΗΝΙΑ { get; set; }
        public Nullable<bool> ΠΑΡΑΔΟΘΗΚΕ { get; set; }
    }
}
