//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΠΕΡΙΟΔΟΙ
    {
        public int PERIOD_ID { get; set; }
        public string ΠΕΡΙΟΔΟΣ { get; set; }
        public Nullable<int> ΧΕ_ΚΩΔ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΕΝΑΡΞΗΣ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΛΗΞΗΣ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public string ΔΙΟΙΚΗΤΗΣ { get; set; }
        public Nullable<int> ΔΙΟΙΚΗΤΗΣ_ΦΥΛΟ { get; set; }
        public string SY_TEXT { get; set; }
    
        public virtual SYS_SCHOOLYEARS SYS_SCHOOLYEARS { get; set; }
    }
}
