//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΠΡΑΚΤΙΚΗ_ΕΛΕΓΧΟΣ
    {
        public int ΕΛΕΓΧΟΣ_ΚΩΔΙΚΟΣ { get; set; }
        public Nullable<int> ΙΕΚ { get; set; }
        public Nullable<int> ΑΜΚ { get; set; }
        public Nullable<int> ΕΡΓΟΔΟΤΗΣ { get; set; }
        public string ΕΛΕΓΚΤΗΣ { get; set; }
        public Nullable<int> ΕΛΕΓΧΟΣ_ΕΞΑΜΗΝΟ { get; set; }
        public Nullable<System.DateTime> ΕΛΕΓΧΟΣ_ΗΜΕΡΟΜΗΝΙΑ { get; set; }
        public Nullable<int> ΜΑΘΗΤΗΣ_ΚΩΔ { get; set; }
    }
}
