//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΠΡΟΓΡΑΜΜΑ_ΑΡΧΕΙΟ
    {
        public int ΠΡΟΓΡΑΜΜΑ_ΚΩΔ { get; set; }
        public int ΙΕΚ { get; set; }
        public int ΚΩΔ_ΤΜΗΜΑ { get; set; }
        public System.DateTime ΗΜΕΡΟΜΗΝΙΑ { get; set; }
        public int ΩΡΑ { get; set; }
        public Nullable<int> ΕΒΔΟΜΑΔΑ { get; set; }
        public Nullable<int> ΚΩΔ_ΜΑΘΗΜΑ { get; set; }
        public Nullable<int> ΚΩΔ_ΕΡΓΑΣΙΑ { get; set; }
        public Nullable<int> ΕΚΠΑΙΔΕΥΤΗΣ1 { get; set; }
        public Nullable<int> ΕΚΠΑΙΔΕΥΤΗΣ2 { get; set; }
        public Nullable<int> ΕΚΠΑΙΔΕΥΤΗΣ3 { get; set; }
        public Nullable<bool> Π1 { get; set; }
        public Nullable<bool> Π2 { get; set; }
        public Nullable<bool> Π3 { get; set; }
    }
}
