//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΠΡΑΚΤΙΚΗ_ΠΑΡΟΥΣΙΑ
    {
        public int ΒΕΒΑΙΩΣΗ_ΚΩΔ { get; set; }
        public Nullable<int> ΙΕΚ { get; set; }
        public Nullable<int> ΑΜΚ { get; set; }
        public Nullable<int> ΕΡΓΟΔΟΤΗΣ { get; set; }
        public Nullable<System.DateTime> ΒΕΒΑΙΩΣΗ_ΗΜΝΙΑ { get; set; }
        public Nullable<bool> ΠΑΡΑΛΑΒΗ { get; set; }
        public Nullable<int> ΜΑΘΗΤΗΣ_ΚΩΔ { get; set; }
        public Nullable<System.DateTime> ΠΡΑΚΤΙΚΗ_ΑΠΟ { get; set; }
        public Nullable<System.DateTime> ΠΡΑΚΤΙΚΗ_ΕΩΣ { get; set; }
        public Nullable<int> ΠΡΑΚΤΙΚΗ_ΩΡΕΣ { get; set; }
        public Nullable<int> ΤΜΗΜΑ_ΚΩΔ { get; set; }
    }
}
