//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΠΡΑΚΤΙΚΗ_ΑΙΤΗΣΗ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ΠΡΑΚΤΙΚΗ_ΑΙΤΗΣΗ()
        {
            this.ΠΡΑΚΤΙΚΗ_ΑΠΟΦΑΣΗ = new HashSet<ΠΡΑΚΤΙΚΗ_ΑΠΟΦΑΣΗ>();
        }
    
        public int ΑΙΤΗΣΗ_ΚΩΔ { get; set; }
        public Nullable<int> ΙΕΚ { get; set; }
        public Nullable<int> ΑΜΚ { get; set; }
        public Nullable<int> ΕΡΓΟΔΟΤΗΣ { get; set; }
        public Nullable<int> ΠΡΩΤΟΚΟΛΛΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΕΡΟΜΗΝΙΑ { get; set; }
        public Nullable<bool> ΥΠΟΒΛΗΘΗΚΕ { get; set; }
        public Nullable<int> ΜΑΘΗΤΗΣ_ΚΩΔ { get; set; }
        public Nullable<int> ΤΜΗΜΑ_ΚΩΔ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΠΡΑΚΤΙΚΗ_ΑΠΟΦΑΣΗ> ΠΡΑΚΤΙΚΗ_ΑΠΟΦΑΣΗ { get; set; }
    }
}
