//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΧΜ_ΕΓΚΥΚΛΙΟΣ_ΕΙΔΙΚΟΤΗΤΕΣ
    {
        public int RECORD_ID { get; set; }
        public int EGYKLIOS_ID { get; set; }
        public int SCHOOL_ID { get; set; }
        public int EIDIKOTITA_ID { get; set; }
        public Nullable<int> TERM_ID { get; set; }
        public Nullable<int> STUDENTS { get; set; }
    
        public virtual ΧΜ_ΕΓΚΥΚΛΙΟΣ ΧΜ_ΕΓΚΥΚΛΙΟΣ { get; set; }
        public virtual ΧΜ_ΕΙΔΙΚΟΤΗΤΕΣ ΧΜ_ΕΙΔΙΚΟΤΗΤΕΣ { get; set; }
    }
}
