//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΧΜ_sqlAITISEIS_HEADERS
    {
        public int ΑΙΤΗΣΗ_ΚΩΔ { get; set; }
        public Nullable<int> ΕΓΚΥΚΛΙΟΣ_ΚΩΔ { get; set; }
        public string ΑΙΤΗΣΗ_ΠΡΩΤΟΚΟΛΛΟ { get; set; }
        public string ΑΦΜ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
    }
}
