//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΧΜ_ΥΠΟΨΗΦΙΟΣ_ΕΜΠΕΙΡΙΑ
    {
        public int ΕΜΠΕΙΡΙΑ_ΚΩΔ { get; set; }
        public Nullable<int> ΑΙΤΗΣΗ_ΚΩΔ { get; set; }
        public Nullable<int> ΕΓΚΥΚΛΙΟΣ_ΚΩΔ { get; set; }
        public Nullable<System.DateTime> ΕΝΑΡΞΗ { get; set; }
        public Nullable<System.DateTime> ΛΗΞΗ { get; set; }
        public string ΠΕΡΙΓΡΑΦΗ { get; set; }
        public Nullable<int> ΔΙΑΡΚΕΙΑ { get; set; }
    
        public virtual ΧΜ_ΥΠΟΨΗΦΙΟΣ ΧΜ_ΥΠΟΨΗΦΙΟΣ { get; set; }
    }
}
