//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΧΜ_ΕΙΔΙΚΟΤΗΤΕΣ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ΧΜ_ΕΙΔΙΚΟΤΗΤΕΣ()
        {
            this.ΧΜ_ΕΓΚΥΚΛΙΟΣ_ΕΙΔΙΚΟΤΗΤΕΣ = new HashSet<ΧΜ_ΕΓΚΥΚΛΙΟΣ_ΕΙΔΙΚΟΤΗΤΕΣ>();
        }
    
        public int EIDIKOTITA_ID { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public Nullable<bool> APPROVED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΧΜ_ΕΓΚΥΚΛΙΟΣ_ΕΙΔΙΚΟΤΗΤΕΣ> ΧΜ_ΕΓΚΥΚΛΙΟΣ_ΕΙΔΙΚΟΤΗΤΕΣ { get; set; }
    }
}
