//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΧΜ_sqlEIDIKOTITA_SELECTOR
    {
        public int RECORD_ID { get; set; }
        public int EGYKLIOS_ID { get; set; }
        public int SCHOOL_ID { get; set; }
        public int EIDIKOTITA_ID { get; set; }
        public string EIDIKOTITA_TERM { get; set; }
        public string TERM { get; set; }
        public int TERM_ID { get; set; }
    }
}
