//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΧΜ_ΥΠΟΨΗΦΙΟΣ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ΧΜ_ΥΠΟΨΗΦΙΟΣ()
        {
            this.ΧΜ_ΥΠΟΨΗΦΙΟΣ_ΕΜΠΕΙΡΙΑ = new HashSet<ΧΜ_ΥΠΟΨΗΦΙΟΣ_ΕΜΠΕΙΡΙΑ>();
        }
    
        public int ΑΙΤΗΣΗ_ΚΩΔ { get; set; }
        public Nullable<int> ΕΓΚΥΚΛΙΟΣ_ΚΩΔ { get; set; }
        public string ΑΙΤΗΣΗ_ΠΡΩΤΟΚΟΛΛΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΕΡΟΜΗΝΙΑ { get; set; }
        public string ΑΦΜ { get; set; }
        public string ΑΜΚΑ { get; set; }
        public string ΕΠΩΝΥΜΟ { get; set; }
        public string ΟΝΟΜΑ { get; set; }
        public string ΠΑΤΡΩΝΥΜΟ { get; set; }
        public string ΜΗΤΡΩΝΥΜΟ { get; set; }
        public Nullable<int> ΦΥΛΟ { get; set; }
        public string ΑΔΤ { get; set; }
        public Nullable<System.DateTime> ΑΔΤ_ΗΜΝΙΑ { get; set; }
        public string ΑΔΤ_ΑΡΧΗ { get; set; }
        public string ΔΗΜΟΣ_ΕΓΓΡΑΦΗΣ { get; set; }
        public string ΑΡ_ΔΗΜΟΤΟΛΟΓΙΟ { get; set; }
        public string ΑΜ_ΑΡΡΕΝΩΝ { get; set; }
        public string ΚΑΤΟΙΚΙΑ_ΠΟΛΗ { get; set; }
        public string ΚΑΤΟΙΚΙΑ_ΔΝΣΗ { get; set; }
        public string ΤΗΛΕΦΩΝΟ { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> ΙΕΚ1 { get; set; }
        public Nullable<int> ΕΙΔΙΚΟΤΗΤΑ1 { get; set; }
        public Nullable<int> ΕΙΔΙΚΟΤΗΤΑ2 { get; set; }
        public Nullable<int> ΕΙΔΙΚΟΤΗΤΑ3 { get; set; }
        public Nullable<int> ΙΕΚ2 { get; set; }
        public Nullable<int> ΕΙΔΙΚΟΤΗΤΑ4 { get; set; }
        public Nullable<int> ΕΙΔΙΚΟΤΗΤΑ5 { get; set; }
        public Nullable<int> ΑΠΟΛΥΤΗΡΙΟ_ΚΩΔ { get; set; }
        public Nullable<decimal> ΒΑΘΜΟΣ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΑΠΟΦΟΙΤΗΣΗ { get; set; }
        public Nullable<bool> ΤΡΙΤΕΚΝΟΣ { get; set; }
        public Nullable<bool> ΠΟΛΥΤΕΚΝΟΣ { get; set; }
        public Nullable<bool> ΜΟΝΟΓΟΝΕΙΚΟΣ { get; set; }
        public Nullable<int> ΕΜΠΕΙΡΙΑ_ΜΗΝΕΣ { get; set; }
        public Nullable<decimal> ΜΟΡΙΑ_ΒΑΘΜΟΣ { get; set; }
        public Nullable<decimal> ΜΟΡΙΑ_ΑΠΟΦΟΙΤΗΣΗ { get; set; }
        public Nullable<decimal> ΜΟΡΙΑ_ΠΟΛΥΤΕΚΝΟΣ { get; set; }
        public Nullable<decimal> ΜΟΡΙΑ_ΤΡΙΤΕΚΝΟΣ { get; set; }
        public Nullable<decimal> ΜΟΡΙΑ_ΜΟΝΟΓΟΝΕΙΚΟΣ { get; set; }
        public Nullable<decimal> ΜΟΡΙΑ_ΕΜΠΕΙΡΙΑ { get; set; }
        public Nullable<decimal> ΜΟΡΙΑ { get; set; }
        public Nullable<int> ΑΠΟΤΕΛΕΣΜΑ { get; set; }
        public Nullable<int> ΕΙΔΙΚΟΤΗΤΑ { get; set; }
        public Nullable<int> ΑΜΚ { get; set; }
        public string ΠΑΡΑΤΗΡΗΣΕΙΣ { get; set; }
        public Nullable<int> ΕΘΝΙΚΟΤΗΤΑ { get; set; }
        public string ΔΙΑΒΑΤΗΡΙΟ { get; set; }
        public Nullable<int> TERM1 { get; set; }
        public Nullable<int> TERM2 { get; set; }
        public Nullable<int> TERM3 { get; set; }
        public Nullable<int> TERM4 { get; set; }
        public Nullable<int> TERM5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΧΜ_ΥΠΟΨΗΦΙΟΣ_ΕΜΠΕΙΡΙΑ> ΧΜ_ΥΠΟΨΗΦΙΟΣ_ΕΜΠΕΙΡΙΑ { get; set; }
    }
}
