//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΧΜ_sqlUPLOADED_FILES
    {
        public Nullable<long> FILE_ID { get; set; }
        public string ID { get; set; }
        public Nullable<int> AITISI_ID { get; set; }
        public Nullable<int> SCHOOL_ID { get; set; }
        public Nullable<int> EGYKLIOS_ID { get; set; }
        public string STUDENT_AFM { get; set; }
        public string UPLOAD_NAME { get; set; }
        public string UPLOAD_SUMMARY { get; set; }
        public string FILENAME { get; set; }
        public string SCHOOL_USER { get; set; }
        public string SCHOOLYEAR_TEXT { get; set; }
        public string EXTENSION { get; set; }
    }
}
