//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΧΜ_sqlΕΠΙΤΥΧΟΝΤΕΣ
    {
        public int ΑΙΤΗΣΗ_ΚΩΔ { get; set; }
        public int ΠΡΟΚΗΡΥΞΗ_ΚΩΔ { get; set; }
        public string ΠΡΟΚΗΡΥΞΗ_ΑΡ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public Nullable<int> ΑΠΟΤΕΛΕΣΜΑ { get; set; }
        public Nullable<int> ΙΕΚ1 { get; set; }
        public Nullable<int> ΕΙΔΙΚΟΤΗΤΑ1 { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public Nullable<int> ΕΞΑΜΗΝΟ1 { get; set; }
        public string ΑΔΤ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public Nullable<decimal> ΜΟΡΙΑ { get; set; }
        public Nullable<decimal> ΜΟΡΙΑ_ΒΑΘΜΟΣ { get; set; }
        public Nullable<decimal> ΜΟΡΙΑ_ΑΠΟΦΟΙΤΗΣΗ { get; set; }
        public Nullable<decimal> ΜΟΡΙΑ_ΕΜΠΕΙΡΙΑ { get; set; }
        public Nullable<decimal> ΜΟΡΙΑ_ΤΡΙΤΕΚΝΟΣ { get; set; }
        public Nullable<decimal> ΜΟΡΙΑ_ΠΟΛΥΤΕΚΝΟΣ { get; set; }
        public Nullable<decimal> ΜΟΡΙΑ_ΜΟΝΟΓΟΝΕΙΚΟΣ { get; set; }
    }
}
