//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΧΜ_UPLOADS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ΧΜ_UPLOADS()
        {
            this.ΧΜ_UPLOADS_FILES = new HashSet<ΧΜ_UPLOADS_FILES>();
        }
    
        public int UPLOAD_ID { get; set; }
        public Nullable<int> EGYKLIOS_ID { get; set; }
        public Nullable<int> AITISI_ID { get; set; }
        public Nullable<int> SCHOOL_ID { get; set; }
        public string STUDENT_AFM { get; set; }
        public Nullable<System.DateTime> UPLOAD_DATE { get; set; }
        public string UPLOAD_NAME { get; set; }
        public string UPLOAD_SUMMARY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΧΜ_UPLOADS_FILES> ΧΜ_UPLOADS_FILES { get; set; }
    }
}
